services:
  - type: web
    name: lavalink-server
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: LAVA_PASS
        sync: false
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: YOUTUBE_CIPHER_URL
        sync: false
      - key: YOUTUBE_CIPHER_PASSWORD
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: KEEP_ALIVE_ENABLED
        value: "true"
